// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	wardle "k8s.io/sample-apiserver/pkg/apis/wardle"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Whitelist2)(nil), (*wardle.Whitelist2)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Whitelist2_To_wardle_Whitelist2(a.(*Whitelist2), b.(*wardle.Whitelist2), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wardle.Whitelist2)(nil), (*Whitelist2)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wardle_Whitelist2_To_v1_Whitelist2(a.(*wardle.Whitelist2), b.(*Whitelist2), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Whitelist2List)(nil), (*wardle.Whitelist2List)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_Whitelist2List_To_wardle_Whitelist2List(a.(*Whitelist2List), b.(*wardle.Whitelist2List), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*wardle.Whitelist2List)(nil), (*Whitelist2List)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_wardle_Whitelist2List_To_v1_Whitelist2List(a.(*wardle.Whitelist2List), b.(*Whitelist2List), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_Whitelist2_To_wardle_Whitelist2(in *Whitelist2, out *wardle.Whitelist2, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ID = in.ID
	out.Ips = *(*[]string)(unsafe.Pointer(&in.Ips))
	out.Name = in.Name
	return nil
}

// Convert_v1_Whitelist2_To_wardle_Whitelist2 is an autogenerated conversion function.
func Convert_v1_Whitelist2_To_wardle_Whitelist2(in *Whitelist2, out *wardle.Whitelist2, s conversion.Scope) error {
	return autoConvert_v1_Whitelist2_To_wardle_Whitelist2(in, out, s)
}

func autoConvert_wardle_Whitelist2_To_v1_Whitelist2(in *wardle.Whitelist2, out *Whitelist2, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.ID = in.ID
	out.Ips = *(*[]string)(unsafe.Pointer(&in.Ips))
	out.Name = in.Name
	return nil
}

// Convert_wardle_Whitelist2_To_v1_Whitelist2 is an autogenerated conversion function.
func Convert_wardle_Whitelist2_To_v1_Whitelist2(in *wardle.Whitelist2, out *Whitelist2, s conversion.Scope) error {
	return autoConvert_wardle_Whitelist2_To_v1_Whitelist2(in, out, s)
}

func autoConvert_v1_Whitelist2List_To_wardle_Whitelist2List(in *Whitelist2List, out *wardle.Whitelist2List, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]wardle.Whitelist2)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_Whitelist2List_To_wardle_Whitelist2List is an autogenerated conversion function.
func Convert_v1_Whitelist2List_To_wardle_Whitelist2List(in *Whitelist2List, out *wardle.Whitelist2List, s conversion.Scope) error {
	return autoConvert_v1_Whitelist2List_To_wardle_Whitelist2List(in, out, s)
}

func autoConvert_wardle_Whitelist2List_To_v1_Whitelist2List(in *wardle.Whitelist2List, out *Whitelist2List, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Whitelist2)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_wardle_Whitelist2List_To_v1_Whitelist2List is an autogenerated conversion function.
func Convert_wardle_Whitelist2List_To_v1_Whitelist2List(in *wardle.Whitelist2List, out *Whitelist2List, s conversion.Scope) error {
	return autoConvert_wardle_Whitelist2List_To_v1_Whitelist2List(in, out, s)
}
